### PR TITLE
Add introductory example

### PR DESCRIPTION
**Pull request by foundinblank**
I've been thinking the README file starts off too intermediate-advanced -- it's why I didn't start using glue for months (because I don't deal with long strings or temporary variables, which were the first 2 examples). To help make the package and its utility more immediately clear to beginners, I've added a simple introductory example explaining glue's most fundamental function -- passing variables to strings.

### CODE REVIEW

**Comment by jimhester** [comment]
Agreed, thanks for the improvement!

**Comment by jimhester** [comment]
The README.md is generated by README.Rmd, could you make this change there, run `rmarkdown::render("README.Rmd")` and commit both files?

**Comment by foundinblank** [comment]
Hmm. I'm really confused now! I pulled my fork to my computer, generated the .md file, but now there's a different example (maybe from someone else?) and my example is gone. 

```
Glue does this by embedding R expressions in curly braces which are then evaluated and inserted into the argument string. For example,

age <- 20
glue('I will soon be {age + 1}.")
yields "I will soon be 21."
```

**Comment by foundinblank** [comment]
Whew! This should be good now. :) Let me know if there's any other problems.

**Comment by jimhester** [comment]
Looks good, thanks!

**Pull request merged**
