### PR TITLE
Add setOldClass for S4 compatibility

### PR DESCRIPTION
**Pull request by gaborcsardi**
Because otherwise glue objects are not treated as
character, by S4 methods. One example is DBI:

```r
library(DBI)
con <- dbConnect(RSQLite::SQLite(), ":memory:")
dbWriteTable(con, "mtcars", mtcars)
dbExecute(con, sqlInterpolate(con, "UPDATE mtcars SET mpg = ?mpg", mpg = glue("100")))
#> Error in (function (classes, fdef, mtable)  :
#>   unable to find an inherited method for function 'dbQuoteString' for signature '"SQLiteConnection", "glue"'
```

### CODE REVIEW

**Comment by jimhester** [comment]
I wonder if we should condition this in `.onLoad()` with `.isMethodDispatchOn()`, otherwise we force loading of the methods package.

**Comment by gaborcsardi** [comment]
But then it will be broken if you load e.g. `DBI` after `glue`.....

**Comment by jimhester** [comment]
We could define the S3 classes as `c("character", "glue")`, then the above and the glue print method work still works. But this would break anytime a `character` method and a `glue` method are defined for the same generic.

`setOldClass` is the right thing to do, I was just trying to avoid loading methods, but I don't think it is possible.

**Comment by jimhester** [comment]
Thanks!

**Pull request merged**
