### PR TITLE
Fix protection errors

### PR DESCRIPTION
**Pull request by krlmlr**
and UTF-8 tests.

@jimhester: Could you please take a look?

@hadley: We might want to wait for this to hit CRAN before releasing dplyr.

### CODE REVIEW

**Comment by jimhester** [comment]
Maybe it would be better to use `PROTECT_WITH_INDEX` and `REPROTECT` rather than `PreserveObject` (https://cran.r-project.org/doc/manuals/R-exts.html#Garbage-Collection)

**Comment by krlmlr** [comment]
I don't know, what's the minimum R version required for these primitives?

**Comment by krlmlr** [comment]
Oh, around October 2000. Should be fine then, will adapt ;-)

**Comment by krlmlr** [comment]
@jimhester: Travis builds look good, AppVeyor seems stuck.

**Comment by jimhester** [comment]
Also `Rf_translateCharUTF8` allocates memory if needed, so I am pretty sure you need to use something like the following to avoid leaking it.

```c
const void* vmax = vmaxget();
# ... code that calls Rf_tranlateCharUTF8
vmaxset(vmax);
```

**Comment by krlmlr** [comment]
The way I read the [documentation](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Memory-allocation), this memory is freed when `.Call()` ends, which should suit our needs.

> This memory is taken from the heap, and released at the end of the .C, .Call or .External call. Users can also manage it ...

**Comment by jimhester** [comment]
Ah, looks like you are correct, I was only looking at the comments above the definition of [translateCharUTF8](https://github.com/wch/r-source/blob/trunk/src/main/sysutils.c#L969-L971).

**Comment by jimhester** [comment]
Thanks!

**Comment by krlmlr** [comment]
Thanks for your quick review. I'd like to tackle #38 next. Have you made any release plans yet?

**Pull request merged**
