### PR TITLE
Glue collapse should always return a single string

### LINKED ISSUE #88: `glue_collapse()` should always return length 1 vectors
``` r
length(glue::glue_collapse(character()))
#> [1] 0
length(glue::glue_collapse(""))
#> [1] 1
length(glue::glue_collapse(letters))
#> [1] 1
```

> Created on 2018-04-13 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Perhaps `glue_collapse()` should always returned a string?

### PR DESCRIPTION
**Pull request by hadley**
Fixes #88

### CODE REVIEW

**Comment by jennybc** [comment]
I don't have a strong opinion on this (at least not yet). But it feels like a big-ish decision worth some discussion.

(I just kicked off cloud revdep checks for this branch, in case that reveals anything interesting.)

This doesn't feel consistent with tidyverse recycling rules. Specifically the one that says anything combined with something of length-0 becomes length-0:

``` r
tibble::tibble(x = integer(), y = 1L)
#> # A tibble: 0 × 2
#> # … with 2 variables: x <int>, y <int>
vctrs::vec_size_common(character())
#> [1] 0
```

Do we think that collapsing has nothing to do with tidyverse recycling rules and thus this doesn't matter?

Or do we think of collapsing as always having a "shadow" empty string `""` as part of the collapsees?

**Comment by jennybc** [comment]
Revdep results:

We checked 614 reverse dependencies (608 from CRAN + 6 from Bioconductor), comparing R CMD check results across CRAN and dev versions of this package.

 * We saw 3 new problems
 * We failed to check 29 packages

These are the 3 packages with new problems: cpp11, lvmisc, tinkr.

The cpp11 result looks obviously related to this. The other two will require a bit more analysis.

(Most of the packages that weren't checked are due to sf not getting installed.)

# cpp11

<details>

* Version: 0.4.3
* GitHub: https://github.com/r-lib/cpp11
* Source code: https://github.com/cran/cpp11
* Date/Publication: 2022-10-12 08:43:54 UTC
* Number of recursive dependencies: 81

Run `revdepcheck::cloud_details(, "cpp11")` for more info

</details>

## Newly broken

*   checking tests ... ERROR
    ```
      Running ‘testthat.R’
    Running the tests in ‘tests/testthat.R’ failed.
    Last 13 lines of output:
       3.   └─base::seq.default(mid, end)
      ── Failure ('test-register.R:222:5'): generate_cpp_functions: returns the empty string if there are no functions ──
      generate_cpp_functions(funs) (`actual`) not equal to character() (`expected`).
      
      `actual`:   ""
      `expected`:   
      ── Failure ('test-register.R:391:5'): generate_r_functions: returns the empty string if there are no functions ──
      generate_r_functions(funs) (`actual`) not equal to character() (`expected`).
      
      `actual`:   ""
      `expected`:   
      
      [ FAIL 3 | WARN 0 | SKIP 2 | PASS 104 ]
      Error: Test failures
      Execution halted
    ```

# lvmisc

<details>

* Version: 0.1.1
* GitHub: https://github.com/verasls/lvmisc
* Source code: https://github.com/cran/lvmisc
* Date/Publication: 2021-04-05 15:20:02 UTC
* Number of recursive dependencies: 136

Run `revdepcheck::cloud_details(, "lvmisc")` for more info

</details>

## Newly broken

*   checking tests ... ERROR
    ```
      Running ‘testthat.R’
    Running the tests in ‘tests/testthat.R’ failed.
    Last 13 lines of output:
      err$message (`actual`) not equal to glue::glue("The method `my_fun` is not yet implemented \\\n      for an object of class `my_class`.") (`expected`).
      
      lines(actual) vs lines(expected)
        "The method `my_fun` is not yet implemented for an object of class `my_class`."
      - ""
      ── Failure ('test-abort.R:109:5'): abort_no_method_for_class() works in objects with multiple classes ──
      err$message (`actual`) not equal to glue::glue("The method `my_fun` is not yet implemented \\\n       for an object of classes `my_class_1` and `my_class_2`.") (`expected`).
      
      lines(actual) vs lines(expected)
        "The method `my_fun` is not yet implemented for an object of classes `my_class_1` and `my_class_2`."
      - ""
      
      [ FAIL 2 | WARN 18 | SKIP 7 | PASS 238 ]
      Error: Test failures
      Execution halted
    ```

# tinkr

<details>

* Version: 0.1.0
* GitHub: https://github.com/ropensci/tinkr
* Source code: https://github.com/cran/tinkr
* Date/Publication: 2022-08-19 12:30:02 UTC
* Number of recursive dependencies: 62

Run `revdepcheck::cloud_details(, "tinkr")` for more info

</details>

## Newly broken

*   checking tests ... ERROR
    ```
      Running ‘testthat.R’
    Running the tests in ‘tests/testthat.R’ failed.
    Last 13 lines of output:
      
      `lines(actual[[2]])` is a character vector ('## Dataset', '', 'The data used:', '[data](https://example.com)', '')
      `lines(expected[[2]])` is absent
      
      [ FAIL 14 | WARN 0 | SKIP 12 | PASS 92 ]
      Deleting unused snapshots:
      • class-yarn/yarn-kilroy.md
      • class-yarn/yarn.Rmd
      • class-yarn/yarn.md
      • to_md/new-code-chunk.Rmd
      • to_md/table.md
      • to_md/to_md-works-for-Rmd.Rmd
      • to_md/to_md-works.md
      Error: Test failures
      Execution halted
    ```

**Comment by DavisVaughan** [comment]
Just adding a quick note, not a full review yet:

I treat collapsing as a summary operation (i.e. `?Summary`) like `min()`/`max()`/`any()`/`all()`, which always return a size 1 result regardless of their inputs. i.e. `any(logical()) == FALSE`.

So I feel like there is a strong support in favor of this change.

The docs also say

> glue_collapse() collapses a character vector of any length into a length 1 vector

Lastly, we may also consider an `na_rm` argument (since summary functions generally always have one) that removes missing values from `x` before collapsing.

**Comment by jennybc** [comment]
Noting also that this PR makes `glue_collapse()` work (more) like `paste(collapse =)`.

``` r
paste(    collapse="|")
#> [1] ""
paste(    collapse="|", recycle0 = TRUE)
#> [1] ""
paste({}, collapse="|")
#> [1] ""
paste({}, collapse="|", recycle0 = TRUE)
#> [1] ""
paste(character(), collapse="|")
#> [1] ""
paste(character(), collapse="|", recycle0 = TRUE)
#> [1] ""
```

<sup>Created on 2023-03-13 with [reprex v2.0.2.9000](https://reprex.tidyverse.org)</sup>

**Comment by jennybc** [comment]
Thanks @DavisVaughan.

I can certainly get on board with this being the right thing to do. In which case, I'll just need to follow up on any associated breakages (which look to be fairly modest).

**Comment by jennybc** [comment]
In particular, this is the sort of principle I was look for. I.e. no the tidyverse recycling rules don't guide us here, but rather this convention around a summary does:

> I treat collapsing as a summary operation (i.e. `?Summary`) like `min()/max()/any()/all()`, which always return a size 1 result regardless of their inputs. i.e. `any(logical()) == FALSE`.

**Comment by jennybc** [comment]
Here's an observation based on the analysis and fixes I made to cpp11, lvmisc, and tinkr.

Sometimes people make a series of calls to `glue_collapse()` or, effectively, nested calls.

In that case, length-0 inputs basically being dropped was actually helpful.

And always returning a length-1 result introduces new, gratuitous newlines in all 3 of cpp11, lvmisc, and tinkr.

Here's a super simplified version of the type of function I found in all 3 packages. Notice how, if the `extra_junk` is missing, the result has a trailing `\n` that is not present when there is both `main_stuff` AND `extra_junk`.

``` r
``` r
library(glue)
packageVersion("glue")
#> [1] '1.6.2.9000'

foo <- function(main_stuff, ...) {
  extra_junk <- list(...)
  extra_junk <- glue_collapse(extra_junk, sep = "\n")
  
  glue_collapse(c(main_stuff, extra_junk), sep = "\n")
}

foo("Hello!", "and", "Goodbye!")
#> Hello!
#> and
#> Goodbye!

unclass(foo("Hello!", "and", "Goodbye!"))
#> [1] "Hello!\nand\nGoodbye!"

foo("Yo!")
#> Yo!

unclass(foo("Yo!"))
#> [1] "Yo!\n"
```

It almost feels like we should make it easy to say "drop length-0 inputs". Something along these lines:

``` r
input <- c("", "hey", "", "", "I herd", "", "you like", "whitespace")
glue_collapse(input, sep = "\n")
#> 
#> hey
#> 
#> 
#> I herd
#> 
#> you like
#> whitespace

glue_collapse(input[nzchar(input)], sep = "\n")
#> hey
#> I herd
#> you like
#> whitespace
```

**Comment by jennybc** [comment]
In all 3 of cpp11, lvmisc, and tinkr, there is (at least) one function that basically makes a series of calls to `glue_collapse()` or, effectively, nested calls.

Therefore, it was actually kind of handy that length-0 inputs effectively disappeared.

With this PR, the fact that `glue_collapse()` returns `""` for the "no input" case creates new, gratuitous newlines in cpp11, lvmisc, and tinkr.

Here's a super simplified version of the type of function I'm describing. Notice the trailing `\n` when I call `foo()` without providing any `extra_junk` via `...`. That trailing `\n` is *not* present if actual `extra_junk` is passed in.

``` r
library(glue)
packageVersion("glue")
#> [1] '1.6.2.9000'

foo <- function(main_stuff, ...) {
  extra_junk <- list(...)
  extra_junk <- glue_collapse(extra_junk, sep = "\n")
  
  glue_collapse(c(main_stuff, extra_junk), sep = "\n")
}

foo("Hello!", "and", "Goodbye!")
#> Hello!
#> and
#> Goodbye!

unclass(foo("Hello!", "and", "Goodbye!"))
#> [1] "Hello!\nand\nGoodbye!"

foo("Yo!")
#> Yo!

unclass(foo("Yo!"))
#> [1] "Yo!\n"
```

It makes me wonder if we should offer a way of telling `glue_collapse()` to drop length-0 inputs. Something along these lines:

``` r
input <- c("", "hey", "", "", "I herd", "", "you like", "whitespace")

glue_collapse(input, sep = "\n")
#> 
#> hey
#> 
#> 
#> I herd
#> 
#> you like
#> whitespace

glue_collapse(input[nzchar(input)], sep = "\n")
#> hey
#> I herd
#> you like
#> whitespace
```

**Comment by jennybc** [comment]
I also note the extra newlines problem goes away if one does "combine then summarize" instead of "summarize, combine, then summarize again". But in real applications sometimes you really have to do the latter.

``` r
library(glue)
packageVersion("glue")
#> [1] '1.6.2.9000'

foo <- function(main_stuff, ...) {
  extra_junk <- list(...)
  extra_junk <- glue_collapse(extra_junk, sep = "\n")
  
  #glue_collapse(c(main_stuff, extra_junk), sep = "\n")
  glue_collapse(c(main_stuff, ...), sep = "\n")
}

foo("Hello!", "and", "Goodbye!")
#> Hello!
#> and
#> Goodbye!

unclass(foo("Hello!", "and", "Goodbye!"))
#> [1] "Hello!\nand\nGoodbye!"

foo("Yo!")
#> Yo!

unclass(foo("Yo!"))
#> [1] "Yo!"
```

**Comment by hadley** [comment]
This isn't exactly the same, but I think it's in the same ballpark: I see a lot of people write code like this:

```R
paste0(c("Hello!", "and", "Goodbye!"), collapse = "\n")
```

But that's actually subtly wrong because it puts a new line in between each line, not at the end of each line. In most cases what I think you actually want is this:

```R
paste0(c("Hello!", "and", "Goodbye!"), "\n", collapse = "")
```

So I don't find that example particularly compelling as a reason to break the very strong convention of "summary functions always return a scalar".

**Review by DavisVaughan — APPROVED** [review]

**Comment by DavisVaughan** [comment]
Somewhat motivating find: we actually have `glue_collapse_data()` that post processes the `glue_collapse()` result to force this size stability by returning `""` in the empty case
https://github.com/r-lib/cpp11/blob/2ddc12f6ab268542c88f4aa24a500682ed260b72/R/utils.R#L1-L7

**Comment by jennybc** [comment]
So @hadley you're basically arguing the exact opposite of what I was seeing in those revdeps. I think it's because the affected `glue_collapse()` usages were mostly generating some sort of message, where that trailing newline doesn't need to be explicit. I.e. we're more likely to do `message("howdy")` than `message("howdy\n")`.

But I'm going to merge this and made the relevant PRs elsewhere. Thanks for the discussion.

**Comment by jennybc** [comment]
> So I don't find that example particularly compelling as a reason to break the very strong convention of "summary functions always return a scalar".

I wasn't proposing to not return a scalar. I was proposing some sort of `compact = TRUE` type of argument that says to drop empty strings, in the presence of at least 1 nonempty string.

**Pull request merged**
